# Generated by Django 4.2.5 on 2023-10-12 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShopAPI', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='good',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ShopAPI.good'),
            preserve_default=False,
        ),
    ]
