# Generated by Django 4.2.5 on 2023-10-12 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopAPI', '0003_token_good'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='good',
        ),
    ]
