# Generated by Django 4.2.5 on 2023-10-12 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShopAPI', '0004_remove_token_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ShopAPI.token'),
        ),
    ]
