# Generated by Django 4.2.5 on 2023-10-12 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopAPI', '0005_good_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='token',
        ),
    ]
