# Generated by Django 4.2.5 on 2023-09-25 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Words', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Words',
            new_name='Word',
        ),
    ]
